name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: false          
      - name: Install dependencies
        run: go get ./cmd/jarversion
      - name: Build
        run: go build -v ./cmd/jarversion/...
      - name: Test with the Go CLI
        run: go test ./cmd/jarversion
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: jarversion
          path: ./dist/*